[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
build_unflags = -Os
build_flags =
    -O1
    -include project_config.h
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit NeoPixel@^1.12.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    https://github.com/me-no-dev/ESPAsyncWebServer.git 
    https://github.com/RobTillaart/DHT20
    adafruit/Adafruit MQTT Library@^2.5.0
    knolleary/PubSubClient@^2.8.0

lib_ignore = 
    WiFi101
    WiFiNINA
    WiFiNINA_Generic
    WiFiNINA - Adafruit Fork
    WiFiNINA_-_Adafruit_Fork
    WebServer
    Ethernet
    EthernetLarge
    ; REMOVED WiFiClientSecure from here - ESP32 needs it!

lib_extra_dirs =
    lib
    lib/Utils

lib_ldf_mode = chain+
lib_compat_mode = strict

board_build.filesystem = spiffs
board_build.partitions = yolo_uno_8MB.csv